### ISSUE TITLE
support/libs missing

### ISSUE THREAD

**Issue by Eduvilascoder** [jbossdemocentral/brms-coolstore-demo-angular-patternfly#1]
Hi Eric,
           Trying to build the dock image, I got this error:
ERROR: Service 'coolstore' failed to build: lstat support/libs: no such file or directory
support/libs directory is missing.
Should I copy that directory from the old coolstore demo?
thanks, Edu Vilas

**Comment by jamesfalkner** [comment]
Hey Edu - whoops, left this off the initial checkin.Fixed!
